name: Continuous Integration/Deployment
on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3

      - name: Setting up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Building AcumaticaXRP.RESTClient
        run:  dotnet build ./Acumatica.RESTClient/AcumaticaXRP.RESTClient.csproj

      - name: Building AcumaticaXRP.Default_20.200.001
        run: dotnet build ./Acumatica.Default_20.200.001/AcumaticaXRP.Default_20.200.001.csproj